version: '3'
services:

  auv_ws:
    container_name: auv_ws
    image: ubuntu
    privileged: true
    environment:
      - DISPLAY=${DISPLAY} 
    volumes:
      - ./../../../catkin_ws:/root/catkin_ws
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/localtime:/etc/localtime
    network_mode: host
    stdin_open: true
    tty: true
